# Generated by Django 5.0.2 on 2024-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lines", models.DecimalField(decimal_places=2, max_digits=9)),
                ("code", models.TextField()),
                ("output", models.TextField()),
            ],
        ),
    ]
